### ISSUE TITLE
Investigar Editores WYSIWYG

### ISSUE THREAD

**Issue by TuGeek** [openECOE/openECOE-WebUI-ng#157]
Investigar la posibilidad de incorporar un editor en la interfaz para generar el informe a medida.
Comprobar que se pueden añadir los atributos al editor para realizar la inserción de forma sencilla.

**Comment by elCrimar** [comment]
**QUILL**
[https://quilljs.com/](url)

**Librerías**
- Gestión de Word: **mammoth**
- Gestión de PDF: **jspdf**
