### ISSUE TITLE
Mejora Página Creación/Edición de Usuarios

### ISSUE THREAD

**Issue by TuGeek** [openECOE/openECOE-WebUI-ng#55]
Como gestor quiero crear o editar usuarios usando un "modal" para facilitar la introducción de información

Actualmente los usuarios se editan en la tabla donde se muestran. Modificar este comportamiento para abrir el modal de creación de usuarios, cargar en los campos actuales los valores actuales y permitir que se actualicen todos los valores y permisos de un usuario.

- [x] Revisar diseño Responsive de la Tabla Usuarios
- [x] Simplificar Edición de Usuario incluyéndolo en el Modal de Creación
- [x] Eliminar código innecesario de edición en línea
- [x] Incluir campo para Cambiar contraseña Usuario

**Comment by omarroal** [comment]
src/app/modules/control-panel/users-admin

**Comment by omarroal** [comment]
src/app/components/action-buttons
