### ISSUE TITLE
Error no carga navbar superior

### ISSUE THREAD

**Issue by omarroal** [openECOE/openECOE-WebUI-ng#71]
Error al recargar la página de la openECOE con F5 no carga la barra de navegación superior.

Posible parámetro que no se carga en el componente.

**Comment by EnriqueLauraB** [comment]
El problema reside en la constante _userData, que cuando se refresca la página pierde los datos del usuario activo, perdiendo en el proceso los permisos del mismo, causando que la navbar superior no cargue.
