### ISSUE TITLE
Error añadir evento "Sin Sonido" causa no adición y posible congelación de la página

### ISSUE THREAD

**Issue by EnriqueLauraB** [openECOE/openECOE-WebUI-ng#76]
Cuando se está creando un nuevo Evento, si se selecciona la opción "Sin Sonido" en las opciones de Sonido, causa que cuando se hace click en Guardar, aparece un nuevo Evento vacío, y si se intenta interactuar con otro elemento de la página, esta se congela, forzando recarga o salida.

**Comment by pasqual-botella** [comment]
El problema ocurre cada segunda creación que se hace en la misma recarga de la página.
